#define MBPL_EXCHANGE		0 // MBPL
#define NSE_EXCHANGE		1
#define BSE_EXCHANGE		2
#define MCX_EXCHANGE		3
#define NCDEX_EXCHANGE		4
#define NSE_CD_EXCHANGE		5
#define DGCX_EXCHANGE		6
//#define MCXSX_EXCHANGE		7      // commented by Priya
#define CME_EXCHANGE		11
//#define USE_EXCHANGE		8   // PRAVIN 22-SEPT-11 

#define MBPL_MARKET			3  // MBPL

#define EQ_MARKET			1
#define FO_MARKET			2 
#define COM_MARKET			3
#define CURR_MARKET			4

#define SPREADORDERLEGS		3
#define HISTORICAL_DATA			0
#define LIVE_DATA				1

#define iORDER_STATUS_REQ					0
#define iORDER_STATUS_REQ_RES				1
#define iORDER_STATUS_REQ_CON				2
#define iORDER_STATUS_REQ_ERR				3
#define iORDER_STATUS_RES_MNG				4
#define iORDER_BATCH_ORDER_CANCEL			5


#define GC_EX_PL_ENTRY_IN					5200			////4000
#define GC_EX_PL_ENTRY_OUT					5201			////4001
#define GC_EX_PL_CONFIRMATION				5202			////4002
#define GC_EX_PL_MOD_IN						5205			////4005
#define GC_EX_PL_MOD_CONFIRMATION			5207			////4007
#define GC_EX_PL_CXL_IN						5208			////4008
#define GC_EX_PL_CXL_OUT					5209			////4009
#define GC_EX_PL_CXL_CONFIRMATION			5210			////4010


#define GC_ORDER_REQ						5501			/// 2000
#define GC_ORDER_RES						5502			/// 2001
#define GC_ORDER_MOD_REQ					5505			/// 2040
#define GC_ORDER_MOD_RES					5506			/// 2041
#define GC_ORDER_MOD_REJ					5507			/// 2042
//#define GC_BOARD_LOT_IN  					5501
//#define GC_BOARD_LOT_OUT  				5502
#define GC_TRADE_CONFIRMATION				5602
//#define GC_ORDER_MOD_IN					5505
//#define GC_ORDER_MOD_OUT					5506
//#define GC_TRADE_MOD_REJ_RES				5607			/// 2288
//#define GC_ORDER_CANCEL_OUT				5509			/// 
//#define GC_ORDER_CANCEL_CONFIRM_RES		5513			/// 2075
#define GC_ORDER_CANCEL_REQ					5508			/// 2070
#define GC_ORDER_CANCEL_RES					5509			/// 2071
#define GC_ORDER_CANCEL_REJ					5510			/// 2072
#define GC_ORDER_CONFIRMATION_RES			5511			/// 2073
#define GC_ORDER_MOD_CONFIRM_RES			5512			/// 2074
#define GC_ORDER_CANCEL_CONFIRM_RES			5513			/// 2075
#define GC_NEG_TRADE_REJ					5514			/// 2076
#define GC_ORDER_ERROR_RES					5516			/// 2231
#define GC_BATCH_ORDER_CANCEL				5517			/// 9002
#define GC_ORDER_FREEZE_RES					5515

#define GC_SURV_ORD_REJ						5531
#define GC_SURV_ORD_MOD_REJ					5532
#define GC_SURV_ORD_CANCEL_REJ				5533	


//#define GC_ORDER_CONFIRMATION				5511
//#define GC_ORDER_MOD_CONFIRMATION			5512

#define GC_LOGIN_RESPONSE					5901
#define GC_LOGIN_REQUEST					5900
#define GC_LOGOFF_REQUEST					5902
#define GC_TOKENMASTER_REQUEST				5910
#define GC_TOKENMASTER_RES_H				5911
#define GC_TOKENMASTER_RES_DATA				5912
#define GC_TOKENMASTER_RES_T				5913

#define GC_LOGOFF_RESPONSE					5903

#define GC_OPEN_POSITION_ADD_REQ			6011
#define GC_OPEN_POSITION_ADD_RES			6012	
#define GC_OPEN_POSITION_MODIFY_REQ			6013
#define GC_OPEN_POSITION_MODIFY_RES			6014
#define GC_OPEN_POSITION_DELETE_REQ			6015
#define GC_OPEN_POSITION_DELETE_RES			6016
#define GC_OPEN_POSITION_VIEW_REQ			6017
#define GC_OPEN_POSITION_VIEW_RES			6018

#define GC_USERMAINTAINANCE_ADD_REQ			6001
#define GC_USERMAINTAINANCE_ADD_RES			6002
#define GC_USERMAINTAINANCE_MODIFY_REQ		6003
#define GC_USERMAINTAINANCE_MODIFY_RES		6004
#define GC_USERMAINTAINANCE_DELETE_REQ		6005
#define GC_USERMAINTAINANCE_DELETE_RES		6006
#define GC_USERMAINTAINANCE_VIEW_REQ		6007
#define GC_USERMAINTAINANCE_VIEW_RES		6008

#define GC_SURVEILLANCE_ADD_REQ				6021
#define GC_SURVEILLANCE_ADD_RES				6022
#define GC_SURVEILLANCE_MODIFY_REQ			6023
#define GC_SURVEILLANCE_MODIFY_RES			6024
#define GC_SURVEILLANCE_DELETE_REQ			6025
#define GC_SURVEILLANCE_DELETE_RES			6026
#define GC_SURVEILLANCE_VIEW_REQ			6027
#define GC_SURVEILLANCE_VIEW_RES			6028

#define GC_USERLOGINDETAIL_VIEW_REQ			6031
#define GC_USERLOGINDETAIL_VIEW_RES			6032

#define	GC_SPREAD_ORD_REQ					5700
#define	GC_SPREAD_ORD_RES					5701
#define	GC_SPREAD_ORD_CONFIRM_RES			5724
#define GC_SPREAD_ORD_MOD_REQ				5718
#define	GC_SPREAD_ORD_MOD_RES				5719
#define	GC_SPREAD_ORD_MOD_CONFIRM_RES		5736
#define	GC_SPREAD_ORD_CANCEL_REQ			5706
#define	GC_SPREAD_ORD_CANCEL_RES			5707
#define	GC_SPREAD_ORD_CANCEL_CONFIRM_RES	5730
#define	GC_SPREAD_ORD_ERROR					5754
#define	GC_SPREAD_ORD_CANCEL_REJ			5727
#define	GC_SPREAD_ORD_MOD_REJ				5733

#define GC_GREEK_2L_ORDER_ENTRY_IN_REQ						5702
#define	GC_GREEK_2L_ORDER_ENTRY_OUT_RES						5703
#define	GC_GREEK_2L_ORDER_CONFIRMATION_RES					5725
#define GC_GREEK_2L_ORDER_ERROR_RES							5755
#define GC_GREEK_2L_ORDER_CXL_CONFIRMATION					5731

#define GC_GREEK_3L_ORDER_ENTRY_IN_REQ						5704
#define	GC_GREEK_3L_ORDER_ENTRY_OUT_RES						5705
#define	GC_GREEK_3L_ORDER_CONFIRMATION_RES					5726
#define GC_GREEK_3L_ORDER_ERROR_RES							5756
#define GC_GREEK_3L_ORDER_CXL_CONFIRMATION					5732
#define GET_EXCHANG_MARKET									1000000//lOurToken or lSequenceNo Divied by GET_EXCHANG_MARKET then We get Exchange Market details
#define BSE_EQ												201


#define BC_MKTWATCH_DEPTH			5004			/// 7208


//#define BASKET_MAGIC_RULE_NUMBER		2000000

//Market Segment Mapping
#define NSE_EQ				101
#define NSE_FO				102
#define	BSE_EQ				201
#define	MCX_COM				303
#define NCDEX_COM			403
#define NSE_CDS				502
//#define MCXSX_CD			702	

#define SYMBOL_SIZE						11
#define INSTRUMENT_NAME_SIZE			7  //
#define COMODITY_ASSET_SIZE				11
#define COMMODITY_GROUP_SIZE			26
#define OPTION_TYPE_SIZE				3
#define CONTRACT_DES_SIZE				26
#define QUOTATION_MATRIC_SIZE			6
#define RECORD_DELETED_SIZE				2
#define REMARKS_SIZE					26
#define MARGIN_INDICATOR_SIZE			2

#define ERROR_LOG_FILE		"QuickInMemoryDll"
#define GENERAL_LOG_FILE	"GeneralQuickInMemoryDll"
